In [41]:
import numpy as np
import matplotlib.pyplot as plt 

In [42]:
from sklearn.model_selection import train_test_split
m=10000

x=np.random.normal(size = m )
X= x.reshape(-1,1)
y=4.*x+3.+np.random.normal(0,3,size = m)

In [43]:
%run C:\Users\bufanx\PycharmProjects\MachineLearning\PlayML\LinearRegression.py

In [44]:
lin_reg = LinearRegression()

In [45]:
lin_reg.fit_sgd(X,y,n_iters=2)

LinearRegression()

In [46]:
lin_reg.coef_

4.034524771502463

In [47]:
lin_reg.interception_

3.049045178241975

In [48]:
from sklearn import datasets

In [60]:
boston = datasets.load_boston()

X=boston.data
y=boston.target

X=X[y<50]
y=y[y<50]

In [61]:
%run C:\Users\bufanx\PycharmProjects\MachineLearning\PlayML\Model_selection.py

In [62]:
X_train,X_test,y_train,y_test = train_test_split(X,y,seed=666)

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
standardScaler = StandardScaler()

In [65]:
standardScaler.fit(X_train)
X_train_standard = standardScaler.transform(X_train)
X_test_standard = standardScaler.transform(X_test)

In [66]:
%time lin_reg.fit_sgd(X_train_standard,y_train,n_iters=2)

Wall time: 3.99 ms


LinearRegression()

In [67]:
lin_reg.coef_

-0.9654125267269917

In [68]:
lin_reg.interception_

21.86212501313427

### scikit-learn中的SGD

In [70]:
from sklearn.linear_model import SGDRegressor

In [74]:
sgd_reg= SGDRegressor()

In [75]:
%time sgd_reg.fit(X_train_standard,y_train)
sgd_reg.score(X_test_standard,y_test)

Wall time: 2.99 ms


0.8129572473421849

### 调试梯度

In [77]:
np.random.seed(666)
X = np.random.random(size=(1000,10))

In [78]:
true_theta = np.arange(1,12,dtype = float)

In [79]:
X_b = np.hstack([np.ones((len(X), 1)), X])

In [80]:
y = X_b.dot(true_theta)+np.random.normal(size =1000)

In [81]:
X.shape

(1000, 10)

In [82]:
y.shape

(1000,)

In [83]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [84]:
def J(theta, X_b,y):
    try:
        return np.sum((y-X_b.dot(theta))**2)/len(X_b)
    except:
        return float('inf')

In [86]:
def dJ_math(theta,X_b,y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(X_b)

In [87]:
def dJ_debug(theta,X_b,y,epsilon=0.01):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta_1 = theta.copy()
        theta_1[i]+=epsilon
        theta_2 = theta.copy()
        theta_2[i]-=epsilon
        res[i]=(J(theta_1,X_b,y)-J(theta_2,X_b,y))/(2*epsilon)
    return res

In [88]:
def gradient_descent(dJ,X_b,y,initial_theta,eta,n_iters=1e4,epsilon =1e-8):
    
    theta = initial_theta
    i_iter = 0
    
    while i_iter < n_iters:
        gradient = dJ(theta,X_b,y)
        last_theta = theta
        theta = theta - eta * gradient
        
        if(abs(J(theta,X_b,y) - J(last_theta,X_b,y))< epsilon):
            break
        
        i_iter += 1
        
    return theta

In [89]:
X_b = np.hstack([np.ones((len(X), 1)), X])

In [90]:
inital_theta = np.zeros(X_b.shape[1])

In [93]:
eta = 0.01

%time theta=gradient_descent(dJ_debug,X_b,y,inital_theta,eta)
theta

Wall time: 3.2 s


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [97]:
%time theta=gradient_descent(dJ_math,X_b,y,inital_theta,eta)
theta

Wall time: 650 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])